default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mustgo_development

test:
  <<: *default
  database: mustgo_test
#     url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: mustgo_production
  username: mustgo
  password: <%= ENV['MUSTGO_DATABASE_PASSWORD'] %>
